{{- if eq .Values.run.mode "CronJob" }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubescout
spec:
  schedule: {{ .Values.run.cronJob.schedule }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          name: kubescout
        spec:
          restartPolicy: Never
          serviceAccountName: {{ .Values.serviceAccount.name | quote }}
          activeDeadlineSeconds: {{ .Values.run.activeDeadlineSeconds }}
          containers:
            - name: kubescout
              image: {{ .Values.image.name }}:{{ .Values.image.tag }}
              imagePullPolicy: {{ .Values.image.imagePullPolicy | quote }}
              {{- if .Values.resources.enable }}
              resources:
                limits:
                  cpu: {{ .Values.resources.limits.cpu | quote }}
                  memory: {{ .Values.resources.limits.memory | quote }}
                requests:
                  cpu: {{ .Values.resources.requests.cpu | quote }}
                  memory: {{ .Values.resources.requests.memory | quote }}
              {{- end }}
              envFrom:
                - configMapRef:
                    name: kubescout-env
              env:
                - name: STORE_FILEPATH
                  value: /var/store/kube-scout.store.json
              {{- if .Values.persistency.enable }}
              volumeMounts:
                - mountPath: "/var/store"
                  name: store
              {{- end }}
          {{- if .Values.persistency.enable }}
          volumes:
            - name: store
              persistentVolumeClaim:
                claimName: kubescout-pvc
          {{- end }}
{{- end }}
