---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubescout-cluster-role
rules:
  - apiGroups: [ "", "apps" ]
    resources: [ "nodes", "namespaces", "deployments", "pods", "events", "replicasets" ]
    verbs: [ "list" ]
  - apiGroups: [ "" ]
    resources: [ "pods/log" ]
    verbs: [ "get" ]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubescout-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubescout-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubescout-cluster-role
subjects:
  - name: kubescout-sa
    kind: ServiceAccount
    namespace: default
