name: "Docker Build"

on:
  push:
    tags:
      - 'v*'

jobs:

  docker-build-push:

    runs-on: ubuntu-latest
    steps:
      - name: Verify latest ci status
        uses: ReallyLiri/verify-latest-workflow@v1.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          OWNER: "ReallyLiri"
          REPOSITORY: "kubescout"
          WORKFLOW: "ci.yaml"
          BRANCH: "main"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "reallyliri"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker meta
        id: dockermeta
        uses: docker/metadata-action@v3
        with:
          images: |
            reallyliri/kubescout
          tags: |
            latest
            type=ref,event=tag

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: reallyliri/kubescout:latest
          tags: ${{ steps.dockermeta.outputs.tags }}
