name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  create-release:

    runs-on: ubuntu-latest
    steps:
      - name: Verify latest ci status
        uses: ReallyLiri/verify-latest-workflow@v1.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          OWNER: "ReallyLiri"
          REPOSITORY: "kubescout"
          WORKFLOW: "ci.yaml"
          BRANCH: "main"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "reallyliri"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\/v/, '');

      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            reallyliri/kubescout:latest
            reallyliri/kubescout:${{ steps.tag.outputs.result }}

      - name: Sync Dockerhub README
        uses: meeDamian/sync-readme@v1.0.6
        with:
          pass: "${{ secrets.DOCKERHUB_TOKEN }}"
          description: "An alerting tool for Kubernetes clusters issues of all types"

      - name: Download latest atrifacts
        run: |
          curl --fail -L -o kubescout-linux.zip https://nightly.link/ReallyLiri/kubescout/workflows/ci.yaml/main/kubescout-linux.zip
          curl --fail -L -o kubescout-osx.zip https://nightly.link/ReallyLiri/kubescout/workflows/ci.yaml/main/kubescout-osx.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kubescout-linux.zip
            kubescout-osx.zip
