name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  create-release:

    runs-on: ubuntu-latest
    steps:
      - name: Get latest ci status
        uses: docker://dwdraju/alpine-curl-jq
        with:
          entrypoint: bash
          args: -c "curl https://_:${{ secrets.GITHUB_TOKEN }}@api.github.com/repos/ReallyLiri/kubescout/actions/workflows/ci.yaml/runs |  jq -r '.workflow_runs[0].status' > ci-status.txt"

      - name: Verify latest ci completed successfully
        run: |
          set -x
          STATUS=$(cat ci-status.txt)
          if [ "$STATUS" != "completed" ]; then
            echo "latest ci run is in status $STATUS, cannot create a release yet"
            exit 1
          fi

      - name: Download latest atrifacts
        run: |
          curl --fail https://nightly.link/ReallyLiri/kubescout/workflows/ci.yaml/main/kubescout-linux.zip
          curl --fail https://nightly.link/ReallyLiri/kubescout/workflows/ci.yaml/main/kubescout-osx.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kubescout-*.zip
