name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  create-release:

    runs-on: ubuntu-latest
    steps:
      - name: Verify latest ci completed successfully
        run: |
          apt-get install -y jq
          STATUS=$(curl https://_:${{ secrets.GITHUB_TOKEN }}@api.github.com/repos/ReallyLiri/kubescout/actions/workflows/ci.yaml/runs |  jq -r '.workflow_runs[0].status')
          if [ "$STATUS" != "completed" ]; then
            echo "latest ci run is in status $STATUS, cannot create a release"
            exit 1
          fi

      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/refs\/tags\/v/, '');

      - name: Download latest atrifacts
        run: |
          curl --fail https://nightly.link/ReallyLiri/kubescout/workflows/ci.yaml/main/kubescout-${{ steps.tag.outputs.result }}-linux.zip
          curl --fail https://nightly.link/ReallyLiri/kubescout/workflows/ci.yaml/main/kubescout-${{ steps.tag.outputs.result }}-osx.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kubescout-*.zip
