name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  create-release:

    runs-on: ubuntu-latest
    steps:
      - name: Verify latest ci status
        uses: ReallyLiri/verify-latest-workflow@v1.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          OWNER: "ReallyLiri"
          REPOSITORY: "kubescout"
          WORKFLOW: "ci.yaml"
          BRANCH: "main"

      - name: Download latest atrifacts
        run: |
          curl --fail -L -o kubescout-linux.zip https://nightly.link/ReallyLiri/kubescout/workflows/ci.yaml/main/kubescout-linux.zip
          curl --fail -L -o kubescout-osx.zip https://nightly.link/ReallyLiri/kubescout/workflows/ci.yaml/main/kubescout-osx.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kubescout-linux.zip
            kubescout-osx.zip
